// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: eligiblediscipline.sql

package sqlc

import (
	"context"
)

const createEligibleDiscipline = `-- name: CreateEligibleDiscipline :exec
INSERT INTO eligible_disciplines (professor_id, discipline_id)
VALUES ($1, $2)
`

type CreateEligibleDisciplineParams struct {
	ProfessorID  int64
	DisciplineID int64
}

func (q *Queries) CreateEligibleDiscipline(ctx context.Context, arg CreateEligibleDisciplineParams) error {
	_, err := q.db.ExecContext(ctx, createEligibleDiscipline, arg.ProfessorID, arg.DisciplineID)
	return err
}

const deleteEligibleDiscipline = `-- name: DeleteEligibleDiscipline :exec
DELETE FROM eligible_disciplines WHERE professor_id = $1 AND discipline_id = $2
`

type DeleteEligibleDisciplineParams struct {
	ProfessorID  int64
	DisciplineID int64
}

func (q *Queries) DeleteEligibleDiscipline(ctx context.Context, arg DeleteEligibleDisciplineParams) error {
	_, err := q.db.ExecContext(ctx, deleteEligibleDiscipline, arg.ProfessorID, arg.DisciplineID)
	return err
}
