// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Availability struct {
	ID          int64
	Uuid        uuid.UUID
	Dayofweek   string
	Shift       string
	ProfessorID int64
}

type Class struct {
	ID           int64
	Uuid         uuid.UUID
	Dayofweek    string
	Shift        string
	Starttime    time.Time
	Endtime      time.Time
	DisciplineID int64
	ProfessorID  int64
	ProposalID   int64
}

type Course struct {
	ID       int64
	Uuid     uuid.UUID
	Name     string
	Modality string
	Location string
}

type Discipline struct {
	ID       int64
	Uuid     uuid.UUID
	Name     string
	Credits  int32
	CourseID int64
}

type EligibleDiscipline struct {
	ID           int64
	ProfessorID  int64
	DisciplineID int64
}

type Parameterization struct {
	ID                      int64
	Uuid                    uuid.UUID
	Maxcreditstooffer       int32
	Numclassesperdiscipline int32
	SemesterID              int64
	CourseID                int64
}

type Professor struct {
	ID              int64
	Uuid            uuid.UUID
	Name            string
	Hourstoallocate int32
}

type Proposal struct {
	ID         int64
	Uuid       uuid.UUID
	SemesterID int64
	CourseID   int64
}

type Semester struct {
	ID       int64
	Uuid     uuid.UUID
	Semester string
}

type User struct {
	ID       int64
	Uuid     uuid.UUID
	Name     string
	Email    string
	Password string
}
