// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Availability struct {
	ID          int64
	Uuid        uuid.UUID
	Dayofweek   string
	Shift       string
	ProfessorID int64
}

type Class struct {
	ID           int64
	Uuid         uuid.UUID
	Dayofweek    string
	Shift        string
	Starttime    time.Time
	Endtime      time.Time
	DisciplineID int64
	ProfessorID  int64
}

type Course struct {
	ID       int64
	Uuid     uuid.UUID
	Name     string
	Modality sql.NullString
	Location sql.NullString
}

type Discipline struct {
	ID       int64
	Uuid     uuid.UUID
	Name     string
	Credits  sql.NullInt32
	CourseID int64
}

type Parameterization struct {
	ID                      int64
	Uuid                    uuid.UUID
	Maxcreditstooffer       sql.NullInt32
	Numclassesperdiscipline sql.NullInt32
	SemesterID              int64
	CourseID                int64
}

type Professor struct {
	ID              int64
	Uuid            uuid.UUID
	Name            string
	Hourstoallocate sql.NullInt32
}

type Proposal struct {
	ID         int64
	Uuid       uuid.UUID
	SemesterID int64
	CourseID   int64
}

type Semester struct {
	ID       int64
	Uuid     uuid.UUID
	Semester string
}

type User struct {
	ID        int64
	Uuid      uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
