// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: parameterization.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :exec
INSERT INTO class (uuid, dayOfWeek, shift, startTime, endTime, discipline_id, professor_id, proposal_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, uuid
`

type CreateClassParams struct {
	Uuid         uuid.UUID
	Dayofweek    string
	Shift        string
	Starttime    time.Time
	Endtime      time.Time
	DisciplineID int64
	ProfessorID  int64
	ProposalID   int64
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) error {
	_, err := q.db.ExecContext(ctx, createClass,
		arg.Uuid,
		arg.Dayofweek,
		arg.Shift,
		arg.Starttime,
		arg.Endtime,
		arg.DisciplineID,
		arg.ProfessorID,
		arg.ProposalID,
	)
	return err
}

const createParameterization = `-- name: CreateParameterization :exec
INSERT INTO parameterization (uuid, maxCreditsToOffer, numClassesPerDiscipline, semester_id, course_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateParameterizationParams struct {
	Uuid                    uuid.UUID
	Maxcreditstooffer       int32
	Numclassesperdiscipline int32
	SemesterID              int64
	CourseID                int64
}

func (q *Queries) CreateParameterization(ctx context.Context, arg CreateParameterizationParams) error {
	_, err := q.db.ExecContext(ctx, createParameterization,
		arg.Uuid,
		arg.Maxcreditstooffer,
		arg.Numclassesperdiscipline,
		arg.SemesterID,
		arg.CourseID,
	)
	return err
}

const createProposal = `-- name: CreateProposal :exec
INSERT INTO proposal (uuid, semester_id, course_id)
VALUES ($1, $2, $3)
`

type CreateProposalParams struct {
	Uuid       uuid.UUID
	SemesterID int64
	CourseID   int64
}

func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) error {
	_, err := q.db.ExecContext(ctx, createProposal, arg.Uuid, arg.SemesterID, arg.CourseID)
	return err
}

const deleteParameterization = `-- name: DeleteParameterization :exec
DELETE FROM parameterization WHERE uuid = $1
`

func (q *Queries) DeleteParameterization(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteParameterization, argUuid)
	return err
}

const findManyParameterizations = `-- name: FindManyParameterizations :many
SELECT p.id, p.uuid, p.maxCreditsToOffer, p.numClassesPerDiscipline, p.semester_id, p.course_id
FROM parameterization p
ORDER BY p.semester_id, p.course_id ASC
`

func (q *Queries) FindManyParameterizations(ctx context.Context) ([]Parameterization, error) {
	rows, err := q.db.QueryContext(ctx, findManyParameterizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parameterization
	for rows.Next() {
		var i Parameterization
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Maxcreditstooffer,
			&i.Numclassesperdiscipline,
			&i.SemesterID,
			&i.CourseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findManyParameterizationsBySemesterId = `-- name: FindManyParameterizationsBySemesterId :many
SELECT p.id, p.uuid, p.maxCreditsToOffer, p.numClassesPerDiscipline, p.semester_id, p.course_id
FROM parameterization p
WHERE p.semester_id = $1
ORDER BY p.course_id ASC
`

func (q *Queries) FindManyParameterizationsBySemesterId(ctx context.Context, semesterID int64) ([]Parameterization, error) {
	rows, err := q.db.QueryContext(ctx, findManyParameterizationsBySemesterId, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parameterization
	for rows.Next() {
		var i Parameterization
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Maxcreditstooffer,
			&i.Numclassesperdiscipline,
			&i.SemesterID,
			&i.CourseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findParameterizationByID = `-- name: FindParameterizationByID :one
SELECT p.id, p.uuid, p.maxCreditsToOffer, p.numClassesPerDiscipline, p.semester_id, p.course_id
FROM parameterization p
WHERE p.uuid = $1
`

func (q *Queries) FindParameterizationByID(ctx context.Context, argUuid uuid.UUID) (Parameterization, error) {
	row := q.db.QueryRowContext(ctx, findParameterizationByID, argUuid)
	var i Parameterization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Maxcreditstooffer,
		&i.Numclassesperdiscipline,
		&i.SemesterID,
		&i.CourseID,
	)
	return i, err
}

const getDisciplinesByCourseID = `-- name: GetDisciplinesByCourseID :many
SELECT id, uuid, name, credits, course_id FROM discipline WHERE course_id = $1
`

func (q *Queries) GetDisciplinesByCourseID(ctx context.Context, courseID int64) ([]Discipline, error) {
	rows, err := q.db.QueryContext(ctx, getDisciplinesByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Discipline
	for rows.Next() {
		var i Discipline
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Credits,
			&i.CourseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParameterizationByID = `-- name: GetParameterizationByID :one
SELECT id, uuid, maxcreditstooffer, numclassesperdiscipline, semester_id, course_id from parameterization p where p.uuid = $1
`

func (q *Queries) GetParameterizationByID(ctx context.Context, argUuid uuid.UUID) (Parameterization, error) {
	row := q.db.QueryRowContext(ctx, getParameterizationByID, argUuid)
	var i Parameterization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Maxcreditstooffer,
		&i.Numclassesperdiscipline,
		&i.SemesterID,
		&i.CourseID,
	)
	return i, err
}

const getProfessorsByCourseID = `-- name: GetProfessorsByCourseID :many
SELECT p.id, p.uuid, p.name, p.hoursToAllocate
FROM professor p
         JOIN eligible_disciplines ed ON p.id = ed.professor_id
         JOIN discipline d ON ed.discipline_id = d.id
WHERE d.course_id = $1
`

func (q *Queries) GetProfessorsByCourseID(ctx context.Context, courseID int64) ([]Professor, error) {
	rows, err := q.db.QueryContext(ctx, getProfessorsByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Professor
	for rows.Next() {
		var i Professor
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Hourstoallocate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProposalID = `-- name: GetProposalID :one
SELECT p.id from proposal p where p.uuid = $1
`

func (q *Queries) GetProposalID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProposalID, argUuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateParameterization = `-- name: UpdateParameterization :exec
UPDATE parameterization SET
    maxCreditsToOffer = COALESCE($2, maxCreditsToOffer),
    numClassesPerDiscipline = COALESCE($3, numClassesPerDiscipline)
WHERE uuid = $1
`

type UpdateParameterizationParams struct {
	Uuid                    uuid.UUID
	MaxCreditsToOffer       sql.NullInt32
	NumClassesPerDiscipline sql.NullInt32
}

func (q *Queries) UpdateParameterization(ctx context.Context, arg UpdateParameterizationParams) error {
	_, err := q.db.ExecContext(ctx, updateParameterization, arg.Uuid, arg.MaxCreditsToOffer, arg.NumClassesPerDiscipline)
	return err
}
